"""creating user and disaster post table

Revision ID: 2260db7329bc
Revises: 23e77fffd853
Create Date: 2020-02-11 01:36:25.851814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2260db7329bc'
down_revision = '23e77fffd853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.drop_table('item_quantity')
    op.drop_index('ix_relief_items_item_name', table_name='relief_items')
    op.drop_table('relief_items')
    op.add_column('disaster_post', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_column('disaster_post', 'id')
    # ### end Alembic commands ###
    '''


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.add_column('disaster_post', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('disaster_post', 'post_id')
    op.create_table('relief_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relief_items_item_name', 'relief_items', ['item_name'], unique=1)
    op.create_table('item_quantity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity_needed', sa.INTEGER(), nullable=True),
    sa.Column('relief_item', sa.INTEGER(), nullable=True),
    sa.Column('disaster', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['disaster'], [u'disaster_post.id'], ),
    sa.ForeignKeyConstraint(['relief_item'], [u'relief_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    '''
