"""disaster items and quantity table created

Revision ID: 23e77fffd853
Revises: e849d6c91dc7
Create Date: 2020-02-11 01:25:18.084167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e77fffd853'
down_revision = 'e849d6c91dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.add_column('disaster_post', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_column('disaster_post', 'id')
    op.add_column('item_quantity', sa.Column('item_quantity_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'item_quantity', type_='foreignkey')
    op.drop_constraint(None, 'item_quantity', type_='foreignkey')
    op.create_foreign_key(None, 'item_quantity', 'relief_items', ['relief_item'], ['item_id'])
    op.create_foreign_key(None, 'item_quantity', 'disaster_post', ['disaster'], ['post_id'])
    op.drop_column('item_quantity', 'id')
    op.add_column('relief_items', sa.Column('item_id', sa.Integer(), nullable=False))
    op.drop_column('relief_items', 'id')
    # ### end Alembic commands ###
    '''


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    op.add_column('relief_items', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('relief_items', 'item_id')
    op.add_column('item_quantity', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'item_quantity', type_='foreignkey')
    op.drop_constraint(None, 'item_quantity', type_='foreignkey')
    op.create_foreign_key(None, 'item_quantity', 'relief_items', ['relief_item'], ['id'])
    op.create_foreign_key(None, 'item_quantity', 'disaster_post', ['disaster'], ['id'])
    op.drop_column('item_quantity', 'item_quantity_id')
    op.add_column('disaster_post', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('disaster_post', 'post_id')
    # ### end Alembic commands ###
    '''
