"""disaster post table created

Revision ID: 2d563e8487af
Revises: e7bd6ea09309
Create Date: 2020-02-10 23:43:53.831180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d563e8487af'
down_revision = 'e7bd6ea09309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('location_latitude', sa.Float(), nullable=True),
    sa.Column('location_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disaster_post_timestamp'), 'disaster_post', ['timestamp'], unique=False)
    op.add_column(u'user', sa.Column('user_status', sa.String(length=10), nullable=True))
    op.add_column(u'user', sa.Column('user_type', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'user_type')
    op.drop_column(u'user', 'user_status')
    op.drop_index(op.f('ix_disaster_post_timestamp'), table_name='disaster_post')
    op.drop_table('disaster_post')
    # ### end Alembic commands ###
