"""creating disaster table

Revision ID: 70d31eeef994
Revises: c69f56890d21
Create Date: 2020-02-11 01:38:49.332537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d31eeef994'
down_revision = 'c69f56890d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('location_latitude', sa.Float(), nullable=True),
    sa.Column('location_longitude', sa.Float(), nullable=True),
    sa.Column('recipient_address', sa.VARCHAR(length=150), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_disaster_post_timestamp'), 'disaster_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disaster_post_timestamp'), table_name='disaster_post')
    op.drop_table('disaster_post')
    # ### end Alembic commands ###
