"""creating user table

Revision ID: c69f56890d21
Revises: 2260db7329bc
Create Date: 2020-02-11 01:38:22.553083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69f56890d21'
down_revision = '2260db7329bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_disaster_post_timestamp', table_name='disaster_post')
    op.drop_table('disaster_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('created_user_id', sa.INTEGER(), nullable=True),
    sa.Column('location_latitude', sa.FLOAT(), nullable=True),
    sa.Column('location_longitude', sa.FLOAT(), nullable=True),
    sa.Column('recipient_address', sa.VARCHAR(length=150), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disaster_post_timestamp', 'disaster_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###
