"""disaster items and quantity table created

Revision ID: e849d6c91dc7
Revises: e513af3c7b03
Create Date: 2020-02-11 01:24:21.474262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e849d6c91dc7'
down_revision = 'e513af3c7b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_quantity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity_needed', sa.Integer(), nullable=True),
    sa.Column('relief_item', sa.Integer(), nullable=True),
    sa.Column('disaster', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disaster'], ['disaster_post.id'], ),
    sa.ForeignKeyConstraint(['relief_item'], ['relief_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_quantity')
    # ### end Alembic commands ###
