"""test for adding col

Revision ID: 311d70a16b86
Revises: 1dea61a9a217
Create Date: 2020-04-19 15:31:48.405425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311d70a16b86'
down_revision = '1dea61a9a217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item')
    op.add_column('Donate', sa.Column('why', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Donate', 'why')
    op.create_table('item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Item')
    # ### end Alembic commands ###
